name: build script for c-basics

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		
        
      - name: Run Tests
        run: make ctest; ./test_script >test_results.txt; gcov ctest-convert.c; gcov ctest-parcer.c

      - name: Upload Test Results 
        if: ${{ always() }} 

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results 
          path: ./ctest

