name: build script for c-basics

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		
        
      - name: Run Tests
        run: |
          make ctest
          ./test_script > test_results.txt
          gcov ctest-convert.c >> test_results2.txt
          gcov ctest-parser.c >> test_results2.txt

      - name: Upload Test Results 
        if: ${{ always() }} 
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results 
          path: ./test_results.txt

      - name: Upload Test Results2
        if: ${{ always() }} 
        uses: actions/upload-artifact@v4
        with:
          name: Test Results GCOV
          path: ./test_results2.txt
